name             'gobgp'
maintainer       'Criteo Network team'
maintainer_email 'network@criteo.com'
license          'Apache-2.0'
description      'Installs/Configure gobgp'
long_description 'Installs/Configure gobgp'
issues_url       'https://github.com/criteo-cookbooks/gobgp/issues'
source_url       'https://github.com/criteo-cookbooks/gobgp'
version          '2.1.0'
supports         'centos'

depends          'ark'
depends          'systemd'
